/*******************************************************************************
 * Copyright (c) 2012 IBM Corporation and others.
 *
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * and Eclipse Distribution License v. 1.0 which accompanies this distribution.
 *  
 * The Eclipse Public License is available at http://www.eclipse.org/legal/epl-v10.html
 * and the Eclipse Distribution License is available at
 * http://www.eclipse.org/org/documents/edl-v10.php.
 *
 * Contributors:
 *
 *     Russell Boykin       - initial API and implementation
 *     Alberto Giammaria    - initial API and implementation
 *     Chris Peters         - initial API and implementation
 *     Gianluca Bernardini  - initial API and implementation
 *     Michael Fiedler      - Bugzilla adpater implementations
 *     Jad El-khoury        - initial implementation of code generator (https://bugs.eclipse.org/bugs/show_bug.cgi?id=422448)
 * 
 * This file is generated by org.eclipse.lyo.oslc4j.codegenerator
 *******************************************************************************/

package com.ericsson.eif.tfs.oslc;

import org.eclipse.lyo.oslc4j.core.model.OslcConstants;

// Start of user code imports
// End of user code

public interface TFSAdapterConstants {
    // Start of user code user constants
    // End of user code

    public static String CHANGE_MANAGEMENT_DOMAIN = "http://open-services.net/ns/cm#";
    public static String CHANGE_MANAGEMENT_NAMSPACE = "http://open-services.net/ns/cm#";
    public static String CHANGE_MANAGEMENT_NAMSPACE_PREFIX = "oslc_cm";

    public static String QUALITY_MANAGEMENT_NAMESPACE = "http://open-services.net/ns/qm#";
    public static String QUALITY_MANAGEMENT_PREFIX = "oslc_qm";
    
    public static String REQUIREMENTS_MANAGEMENT_NAMESPACE = "http://open-services.net/ns/rm#";
    public static String REQUIREMENTS_MANAGEMENT_PREFIX = "oslc_rm";
    
    public static String SOFTWARE_CONFIGURATION_MANAGEMENT_NAMESPACE = "http://open-services.net/ns/scm#";
    public static String SOFTWARE_CONFIGURATION_MANAGEMENT_PREFIX = "oslc_scm";
    
    public static String DUBLIN_CORE_DOMAIN = "http://purl.org/dc/terms#";
    public static String DUBLIN_CORE_NAMSPACE = "http://purl.org/dc/terms#";
    public static String DUBLIN_CORE_NAMSPACE_PREFIX = "dcterms";

    public static String FOAF_DOMAIN = "http://xmlns.com/foaf/0.1#";
    public static String FOAF_NAMSPACE = "http://xmlns.com/foaf/0.1#";
    public static String FOAF_NAMSPACE_PREFIX = "foaf";

    public static String OSLC_CORE_DOMAIN = "http://open-services.net/ns/core#";
    public static String OSLC_CORE_NAMSPACE = "http://open-services.net/ns/core#";
    public static String OSLC_CORE_NAMSPACE_PREFIX = "oslc";

    public static String RDF_DOMAIN = "http://www.w3.org/1999/02/22-rdf-syntax-ns#";
    public static String RDF_NAMSPACE = "http://www.w3.org/1999/02/22-rdf-syntax-ns#";
    public static String RDF_NAMSPACE_PREFIX = "rdf";

    public static String TFSBUG_DOMAIN = "http://www.microsoft.com/tfs#";
    public static String TFSBUG_NAMSPACE = "http://www.microsoft.com/tfs#";
    public static String TFSBUG_NAMSPACE_PREFIX = "tfsbug";

    public static String CHANGEREQUEST = "ChangeRequest";
    public static String PATH_CHANGEREQUEST = "changeRequest";
    public static String TYPE_CHANGEREQUEST = CHANGE_MANAGEMENT_NAMSPACE
            + "ChangeRequest";
    public static String PERSON = "person";
    public static String PATH_PERSON = "person";
    public static String TYPE_PERSON = FOAF_NAMSPACE + "Person";
    public static String TFSCHANGEREQUEST = "tFSChangeRequest";
    public static String PATH_TFSCHANGEREQUEST = "tFSChangeRequest";
    public static String TYPE_TFSCHANGEREQUEST = TFSBUG_NAMSPACE
            + "TFSChangeRequest";
    public static String TYPE = "type";
    public static String PATH_TYPE = "type";
    public static String TYPE_TYPE = DUBLIN_CORE_NAMSPACE + "Type";
    
    public static String TYPE_REQUIREMENT = REQUIREMENTS_MANAGEMENT_NAMESPACE
            + "Requirement";
    public static String TYPE_TEST_CASE = QUALITY_MANAGEMENT_NAMESPACE
            + "TestCase";
    public static String TYPE_TEST_EXECUTION_RECORD = QUALITY_MANAGEMENT_NAMESPACE
            + "TestExecutionRecord";
    public static String TYPE_TEST_PLAN = QUALITY_MANAGEMENT_NAMESPACE
            + "TestPlan";
    public static String TYPE_TEST_RESULT = QUALITY_MANAGEMENT_NAMESPACE
            + "TestResult";
    public static String TYPE_TEST_SCRIPT = QUALITY_MANAGEMENT_NAMESPACE
            + "TestScript";
    public static String TYPE_CHANGE_SET = SOFTWARE_CONFIGURATION_MANAGEMENT_NAMESPACE
            + "ChangeSet";
    public static String TYPE_DISCUSSION = OslcConstants.OSLC_CORE_NAMESPACE
            + "Discussion";

    public static String ENTERPRISE_CHANGE_MANAGEMENT_DOMAIN = "http://mhweb.ericsson.com/rdf#";
    public static String ENTERPRISE_CHANGE_MANAGEMENT_NAMESPACE = "http://mhweb.ericsson.com/rdf#";
    public static String ENTERPRISE_CHANGE_MANAGEMENT_PREFIX = "ecm";
    
    public static String ENTERPRISE_CHANGE_REQUEST = "EnterpriseChangeRequest";
    public static String PATH_ENTERPRISE_CHANGE_REQUEST = "enterpriseChangeRequest";
    public static String TYPE_ENTERPRISE_CHANGE_REQUEST = ENTERPRISE_CHANGE_MANAGEMENT_NAMESPACE
            + ENTERPRISE_CHANGE_REQUEST;
    
    public static final String HDR_OSLC_VERSION = "OSLC-Core-Version";

}
