<!-- <!DOCTYPE html> -->
<%-- <%-- --%>
<%--  Copyright (c) 2011, 2012 IBM Corporation and others. --%>

<%--  All rights reserved. This program and the accompanying materials --%>
<%--  are made available under the terms of the Eclipse Public License v1.0 --%>
<%--  and Eclipse Distribution License v. 1.0 which accompanies this distribution. --%>
 
<%--  The Eclipse Public License is available at http://www.eclipse.org/legal/epl-v10.html --%>
<%--  and the Eclipse Distribution License is available at --%>
<%--  http://www.eclipse.org/org/documents/edl-v10.php. --%>
 
<%--  Contributors: --%>
 
<%--     Sam Padgett 	 - initial API and implementation --%>
<%--     Michael Fiedler	 - adapted for OSLC4J --%>
<%-- 	Jad El-khoury        - initial implementation of code generator (https://bugs.eclipse.org/bugs/show_bug.cgi?id=422448) --%>

<%--  This file is generated by org.eclipse.lyo.oslc4j.codegenerator --%>
<%-- --%> --%>

<%-- <%@page import="org.eclipse.lyo.oslc4j.core.model.ServiceProvider"%> --%>
<%-- <%@page import="java.util.List" %> --%>
<%-- <%@page import="com.ericsson.eif.tfs.oslc.resources.ChangeRequest"%> --%>
<%-- <%-- --%>
<%-- Start of user code imports --%>
<%-- --%> --%>
<%-- <%--  --%>
<%-- End of user code  --%>
<%-- --%> --%>


<%-- <%@ page contentType="text/html" language="java" pageEncoding="UTF-8" %> --%>

<%-- <% --%>
// 	ServiceProvider serviceProvider = (ServiceProvider) request.getAttribute("serviceProvider");
<%-- %> --%>
<%-- <%-- --%>
<%-- Start of user code getRequestAttributes --%>
<%-- --%> --%>
<%-- <%-- --%>
<%-- End of user code --%>
<%-- --%> --%>

<!-- <html> -->
<!-- 	<head> -->
<!-- 		<meta http-equiv="Content-Type" content="text/html;charset=utf-8"> -->
<!-- 		<title>Resource Creator</title> -->
<%-- 		<%--  --%>
<%-- Start of user code (RECOMMENDED) headStuff  --%>
<%-- 		--%> --%>
<%-- 		<%--  --%>
<%-- End of user code  --%>
<%-- 		--%> --%>
<!-- 	</head> -->
<!-- 	<body style="padding: 10px;"> -->
<!-- 		<div id="bugzilla-body"> -->
<!-- 		<form id="Create" method="POST" class="enter_bug_form"> -->
<%-- 		<%--  --%>
<%-- Start of user code (RECOMMENDED) formStuff  --%>
<%-- 		--%> --%>
<%-- 		<%--  --%>
<%-- End of user code  --%>
<%-- 		--%> --%>
<!-- 				<table style="clear: both;"> -->

<!-- 						<tr> -->
<%-- 							<td><%= ChangeRequest.affectedByDefectsAsHtmlForCreation(request, serviceProvider.getIdentifier())%></td> --%>
<!-- 						</tr> -->
<!-- 						<tr> -->
<%-- 							<td><%= ChangeRequest.affectsPlanItemsAsHtmlForCreation(request, serviceProvider.getIdentifier())%></td> --%>
<!-- 						</tr> -->
<!-- 						<tr> -->
<%-- 							<td><%= ChangeRequest.affectsRequirementsAsHtmlForCreation(request, serviceProvider.getIdentifier())%></td> --%>
<!-- 						</tr> -->
<!-- 						<tr> -->
<%-- 							<td><%= ChangeRequest.affectsTestResultsAsHtmlForCreation(request, serviceProvider.getIdentifier())%></td> --%>
<!-- 						</tr> -->
<!-- 						<tr> -->
<%-- 							<td><%= ChangeRequest.blocksTestExecutionRecordsAsHtmlForCreation(request, serviceProvider.getIdentifier())%></td> --%>
<!-- 						</tr> -->
<!-- 						<tr> -->
<%-- 							<td><%= ChangeRequest.contributorsAsHtmlForCreation(request, serviceProvider.getIdentifier())%></td> --%>
<!-- 						</tr> -->
<!-- 						<tr> -->
<%-- 							<td><%= ChangeRequest.creatorsAsHtmlForCreation(request, serviceProvider.getIdentifier())%></td> --%>
<!-- 						</tr> -->
<!-- 						<tr> -->
<%-- 							<td><%= ChangeRequest.dctermsTypesAsHtmlForCreation(request, serviceProvider.getIdentifier())%></td> --%>
<!-- 						</tr> -->
<!-- 						<tr> -->
<%-- 							<td><%= ChangeRequest.implementsRequirementsAsHtmlForCreation(request, serviceProvider.getIdentifier())%></td> --%>
<!-- 						</tr> -->
<!-- 						<tr> -->
<%-- 							<td><%= ChangeRequest.relatedChangeRequestsAsHtmlForCreation(request, serviceProvider.getIdentifier())%></td> --%>
<!-- 						</tr> -->
<!-- 						<tr> -->
<%-- 							<td><%= ChangeRequest.relatedTestCasesAsHtmlForCreation(request, serviceProvider.getIdentifier())%></td> --%>
<!-- 						</tr> -->
<!-- 						<tr> -->
<%-- 							<td><%= ChangeRequest.relatedTestExecutionRecordsAsHtmlForCreation(request, serviceProvider.getIdentifier())%></td> --%>
<!-- 						</tr> -->
<!-- 						<tr> -->
<%-- 							<td><%= ChangeRequest.relatedTestPlansAsHtmlForCreation(request, serviceProvider.getIdentifier())%></td> --%>
<!-- 						</tr> -->
<!-- 						<tr> -->
<%-- 							<td><%= ChangeRequest.relatedTestScriptsAsHtmlForCreation(request, serviceProvider.getIdentifier())%></td> --%>
<!-- 						</tr> -->
<!-- 						<tr> -->
<%-- 							<td><%= ChangeRequest.subjectsAsHtmlForCreation(request, serviceProvider.getIdentifier())%></td> --%>
<!-- 						</tr> -->
<!-- 						<tr> -->
<%-- 							<td><%= ChangeRequest.testedByTestCasesAsHtmlForCreation(request, serviceProvider.getIdentifier())%></td> --%>
<!-- 						</tr> -->
<!-- 						<tr> -->
<%-- 							<td><%= ChangeRequest.tracksChangeSetsAsHtmlForCreation(request, serviceProvider.getIdentifier())%></td> --%>
<!-- 						</tr> -->
<!-- 						<tr> -->
<%-- 							<td><%= ChangeRequest.tracksRequirementsAsHtmlForCreation(request, serviceProvider.getIdentifier())%></td> --%>
<!-- 						</tr> -->
<!-- 						<tr> -->
<%-- 							<td><%= ChangeRequest.rdfTypesAsHtmlForCreation(request, serviceProvider.getIdentifier())%></td> --%>
<!-- 						</tr> -->
<!-- 						<tr> -->
<%-- 							<td><%= ChangeRequest.approvedAsHtmlForCreation(request, serviceProvider.getIdentifier())%></td> --%>
<!-- 						</tr> -->
<!-- 						<tr> -->
<%-- 							<td><%= ChangeRequest.closedAsHtmlForCreation(request, serviceProvider.getIdentifier())%></td> --%>
<!-- 						</tr> -->
<!-- 						<tr> -->
<%-- 							<td><%= ChangeRequest.closeDateAsHtmlForCreation(request, serviceProvider.getIdentifier())%></td> --%>
<!-- 						</tr> -->
<!-- 						<tr> -->
<%-- 							<td><%= ChangeRequest.createdAsHtmlForCreation(request, serviceProvider.getIdentifier())%></td> --%>
<!-- 						</tr> -->
<!-- 						<tr> -->
<%-- 							<td><%= ChangeRequest.descriptionAsHtmlForCreation(request, serviceProvider.getIdentifier())%></td> --%>
<!-- 						</tr> -->
<!-- 						<tr> -->
<%-- 							<td><%= ChangeRequest.discussedByAsHtmlForCreation(request, serviceProvider.getIdentifier())%></td> --%>
<!-- 						</tr> -->
<!-- 						<tr> -->
<%-- 							<td><%= ChangeRequest.fixedAsHtmlForCreation(request, serviceProvider.getIdentifier())%></td> --%>
<!-- 						</tr> -->
<!-- 						<tr> -->
<%-- 							<td><%= ChangeRequest.identifierAsHtmlForCreation(request, serviceProvider.getIdentifier())%></td> --%>
<!-- 						</tr> -->
<!-- 						<tr> -->
<%-- 							<td><%= ChangeRequest.inprogressAsHtmlForCreation(request, serviceProvider.getIdentifier())%></td> --%>
<!-- 						</tr> -->
<!-- 						<tr> -->
<%-- 							<td><%= ChangeRequest.instanceShapeAsHtmlForCreation(request, serviceProvider.getIdentifier())%></td> --%>
<!-- 						</tr> -->
<!-- 						<tr> -->
<%-- 							<td><%= ChangeRequest.modifiedAsHtmlForCreation(request, serviceProvider.getIdentifier())%></td> --%>
<!-- 						</tr> -->
<!-- 						<tr> -->
<%-- 							<td><%= ChangeRequest.reviewedAsHtmlForCreation(request, serviceProvider.getIdentifier())%></td> --%>
<!-- 						</tr> -->
<!-- 						<tr> -->
<%-- 							<td><%= ChangeRequest.serviceProviderAsHtmlForCreation(request, serviceProvider.getIdentifier())%></td> --%>
<!-- 						</tr> -->
<!-- 						<tr> -->
<%-- 							<td><%= ChangeRequest.shortTitleAsHtmlForCreation(request, serviceProvider.getIdentifier())%></td> --%>
<!-- 						</tr> -->
<!-- 						<tr> -->
<%-- 							<td><%= ChangeRequest.statusAsHtmlForCreation(request, serviceProvider.getIdentifier())%></td> --%>
<!-- 						</tr> -->
<!-- 						<tr> -->
<%-- 							<td><%= ChangeRequest.titleAsHtmlForCreation(request, serviceProvider.getIdentifier())%></td> --%>
<!-- 						</tr> -->
<!-- 						<tr> -->
<%-- 							<td><%= ChangeRequest.verifiedAsHtmlForCreation(request, serviceProvider.getIdentifier())%></td> --%>
<!-- 						</tr> -->

					
<!-- 					<tr> -->
<!-- 						<td></td> -->
<!-- 						<td> -->
<!-- 							<input type="submit" value="Submit"> -->
<!-- 							<input type="reset"> -->
<!-- 						</td> -->
<!-- 					</tr> -->
<!-- 				</table> -->
				

<!-- 				<div style="width: 500px;"> -->
					
<!-- 				</div> -->
				
<!-- 			</form> -->

<!-- 			<div style="clear: both;"></div> -->
<!-- 		</div> -->
<!-- 	</body> -->
<!-- </html> -->



