/*******************************************************************************
 * Copyright (c) 2012 IBM Corporation and others.
 *
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * and Eclipse Distribution License v. 1.0 which accompanies this distribution.
 *  
 * The Eclipse Public License is available at http://www.eclipse.org/legal/epl-v10.html
 * and the Eclipse Distribution License is available at
 * http://www.eclipse.org/org/documents/edl-v10.php.
 *
 * Contributors:
 *
 *     Russell Boykin       - initial API and implementation
 *     Alberto Giammaria    - initial API and implementation
 *     Chris Peters         - initial API and implementation
 *     Gianluca Bernardini  - initial API and implementation
 *	   Sam Padgett	       - initial API and implementation
 *     Michael Fiedler     - adapted for OSLC4J
 *     Jad El-khoury        - initial implementation of code generator (https://bugs.eclipse.org/bugs/show_bug.cgi?id=422448)
 *
 * This file is generated by org.eclipse.lyo.oslc4j.codegenerator
 *******************************************************************************/


package com.ericsson.eif.tfs.oslc.resources;

import java.net.URI;
import java.net.URISyntaxException;
import java.util.Arrays;
import java.util.HashSet;
import java.util.Set;

import org.eclipse.lyo.oslc4j.core.annotation.OslcAllowedValue;
import org.eclipse.lyo.oslc4j.core.annotation.OslcDescription;
import org.eclipse.lyo.oslc4j.core.annotation.OslcName;
import org.eclipse.lyo.oslc4j.core.annotation.OslcNamespace;
import org.eclipse.lyo.oslc4j.core.annotation.OslcOccurs;
import org.eclipse.lyo.oslc4j.core.annotation.OslcPropertyDefinition;
import org.eclipse.lyo.oslc4j.core.annotation.OslcResourceShape;
import org.eclipse.lyo.oslc4j.core.annotation.OslcTitle;
import org.eclipse.lyo.oslc4j.core.annotation.OslcValueType;
import org.eclipse.lyo.oslc4j.core.model.Link;
import org.eclipse.lyo.oslc4j.core.model.Occurs;
import org.eclipse.lyo.oslc4j.core.model.ValueType;

import com.ericsson.eif.tfs.oslc.TFSAdapterConstants;
// Start of user code imports
// End of user code

@OslcNamespace(TFSAdapterConstants.ENTERPRISE_CHANGE_MANAGEMENT_NAMESPACE)
@OslcName(TFSAdapterConstants.ENTERPRISE_CHANGE_REQUEST) 
@OslcResourceShape(title = "EnterpriseChangeRequest Resource Shape", describes = TFSAdapterConstants.TYPE_ENTERPRISE_CHANGE_REQUEST)
public class EnterpriseChangeRequest
       extends ChangeRequest
       
{
    // From OSLC

    // From ecm domain.
    private String answer;
    private String answerCode;
    private String currentMho;
    private String diddet;
    private String faultCode;
    private String firstTechnicalContact;
    private String product;
    private String productRevision;
    private String nodeProduct;
    private String nodeProductRevision;
    private String correctedProduct;
    private String correctedProductRevision;
    private String correctedNodeProduct;
    private String correctedNodeProductRevision;
    private String firstTechContactInfo;
    private String activity;
    private String customer;
    private String country;
    private String site;
    private String impactOnISP;
    private String expectedImpactOnISP;
    private String notebook;
    private String progressInfo;
    private String duplicateTRs;
    private final Set<Link> attachments = new HashSet<Link>();

    // Temporary ecm domain.
    private String priority;
    private String owner;
	
	public EnterpriseChangeRequest()
	       throws URISyntaxException
	{
	    super();
	
		// Start of user code constructor1
		URI[] rdfTypes = new URI[1];
		rdfTypes[0] = new URI(TFSAdapterConstants.TYPE_ENTERPRISE_CHANGE_REQUEST);
		setRdfTypes(rdfTypes);
		// End of user code
	}

	public EnterpriseChangeRequest(final URI about)
	       throws URISyntaxException
	{
	    super(about);
	
		// Start of user code constructor2
		URI[] rdfTypes = new URI[1];
		rdfTypes[0] = new URI(TFSAdapterConstants.TYPE_ENTERPRISE_CHANGE_REQUEST);
		setRdfTypes(rdfTypes);
		// End of user code
	}

    // ==========================================================
    // To be replaced with corresponding OSLC CM constructs

    @OslcDescription("TBD Description")
    @OslcPropertyDefinition(TFSAdapterConstants.ENTERPRISE_CHANGE_MANAGEMENT_NAMESPACE + "answer")
    @OslcTitle("Answer")
    @OslcValueType(ValueType.XMLLiteral)
    public String getAnswer() {
        return answer;
    }

    @OslcDescription("TBD Description")
    @OslcPropertyDefinition(TFSAdapterConstants.ENTERPRISE_CHANGE_MANAGEMENT_NAMESPACE + "answerCode")
    @OslcTitle("AnswerCode")
    @OslcValueType(ValueType.XMLLiteral)
    public String getAnswerCode() {
        return answerCode;
    }

    @OslcDescription("TBD Description")
    @OslcPropertyDefinition(TFSAdapterConstants.ENTERPRISE_CHANGE_MANAGEMENT_NAMESPACE + "faultCode")
    @OslcTitle("FaultCode")
    @OslcValueType(ValueType.XMLLiteral)
    public String getFaultCode() {
        return faultCode;
    }

    @OslcDescription("TBD Description")
    @OslcPropertyDefinition(TFSAdapterConstants.ENTERPRISE_CHANGE_MANAGEMENT_NAMESPACE + "firstTechnicalContact")
    @OslcTitle("FirstTechnicalContact")
    @OslcValueType(ValueType.XMLLiteral)
    public String getFirstTechnicalContact() {
        return firstTechnicalContact;
    }
    
    @OslcDescription("The owner.")
    @OslcPropertyDefinition(TFSAdapterConstants.ENTERPRISE_CHANGE_MANAGEMENT_NAMESPACE + "owner")
    @OslcTitle("Owner")
    @OslcValueType(ValueType.XMLLiteral)
    public String getOwner()
    {
        return owner;
    }
    
    @OslcAllowedValue({ "A", "B", "C"})
    @OslcDescription("The MHWeb priority.")
    @OslcPropertyDefinition(TFSAdapterConstants.ENTERPRISE_CHANGE_MANAGEMENT_NAMESPACE + "priority")
    @OslcTitle("MH Priority")
    @OslcValueType(ValueType.String)
    public String getPriority()
    {
        return priority;
    }

    // ==========================================================

    @OslcDescription("When the defect was detected - DID DETECT.")
    @OslcPropertyDefinition(TFSAdapterConstants.ENTERPRISE_CHANGE_MANAGEMENT_NAMESPACE + "diddet")
    @OslcOccurs(Occurs.ZeroOrOne)
    @OslcTitle("DIDDET")
    public String getDiddet()
    {
        return diddet;
    }

    @OslcDescription("The activity")
    @OslcPropertyDefinition(TFSAdapterConstants.ENTERPRISE_CHANGE_MANAGEMENT_NAMESPACE + "activity")
    @OslcOccurs(Occurs.ZeroOrOne)
    @OslcTitle("Activity")
    public String getActivity()
    {
        return activity;
    }
    
    @OslcDescription("The Customer who reported the issue.")
    @OslcPropertyDefinition(TFSAdapterConstants.ENTERPRISE_CHANGE_MANAGEMENT_NAMESPACE + "customer")
    @OslcOccurs(Occurs.ZeroOrOne)
    @OslcTitle("Customer")
    public String getCustomer() {
        return customer;
    }
    

    @OslcDescription("Where was the issue reported.")
    @OslcPropertyDefinition(TFSAdapterConstants.ENTERPRISE_CHANGE_MANAGEMENT_NAMESPACE + "country")
    @OslcOccurs(Occurs.ZeroOrOne)
    @OslcTitle("Country")
    public String getCountry() {
        return country;
    }
    
    @OslcDescription("At what customer site was the issue reported.")
    @OslcPropertyDefinition(TFSAdapterConstants.ENTERPRISE_CHANGE_MANAGEMENT_NAMESPACE + "site")
    @OslcOccurs(Occurs.ZeroOrOne)
    @OslcTitle("Site")
    public String getSite() {
        return site;
    }
    
    @OslcDescription("The experienced customer ISP (In Service Performance) code and the explanation.")
    @OslcPropertyDefinition(TFSAdapterConstants.ENTERPRISE_CHANGE_MANAGEMENT_NAMESPACE + "impactOnISP")
    @OslcOccurs(Occurs.ZeroOrOne)
    @OslcTitle("Experienced Impact On ISP")
    public String getImpactOnISP() {
        return impactOnISP;
    }

    @OslcDescription("The notebook entry")
    @OslcPropertyDefinition(TFSAdapterConstants.ENTERPRISE_CHANGE_MANAGEMENT_NAMESPACE + "notebook")
    @OslcOccurs(Occurs.ZeroOrOne)
    @OslcTitle("The notebook entry")
    public String getNotebook() {
        return notebook;
    }

    @OslcDescription("The progress info entry")
    @OslcPropertyDefinition(TFSAdapterConstants.ENTERPRISE_CHANGE_MANAGEMENT_NAMESPACE + "progressInfo")
    @OslcOccurs(Occurs.ZeroOrOne)
    @OslcTitle("The progress info entry")
    public String getProgressInfo() {
        return progressInfo;
    }
    
    @OslcDescription("Who the first technical contact is.")
    @OslcPropertyDefinition(TFSAdapterConstants.ENTERPRISE_CHANGE_MANAGEMENT_NAMESPACE + "firstTechContactInfo")
    @OslcOccurs(Occurs.ZeroOrOne)
    @OslcTitle("First Technical Contact")
    public String getFirstTechContactInfo()
    {
        return firstTechContactInfo;
    }

    @OslcDescription("The MHO.")
    @OslcPropertyDefinition(TFSAdapterConstants.ENTERPRISE_CHANGE_MANAGEMENT_NAMESPACE + "currentMho")
    @OslcOccurs(Occurs.ExactlyOne)
    @OslcTitle("Current MHO")
    public String getCurrentMho()
    {
        return currentMho;
    }

    @OslcDescription("The Product.")
    @OslcPropertyDefinition(TFSAdapterConstants.ENTERPRISE_CHANGE_MANAGEMENT_NAMESPACE + "product")
    @OslcOccurs(Occurs.ExactlyOne)
    @OslcTitle("Product")
    public String getProduct()
    {
        return product;
    }

    @OslcDescription("The Product Revision.")
    @OslcPropertyDefinition(TFSAdapterConstants.ENTERPRISE_CHANGE_MANAGEMENT_NAMESPACE + "productRevision")
    @OslcOccurs(Occurs.ExactlyOne)
    @OslcTitle("Product Revision")
    public String getProductRevision()
    {
        return productRevision;
    }

    @OslcDescription("The Node Product.")
    @OslcPropertyDefinition(TFSAdapterConstants.ENTERPRISE_CHANGE_MANAGEMENT_NAMESPACE + "nodeProduct")
    @OslcOccurs(Occurs.ZeroOrOne)
    @OslcTitle("Node Product")
    public String getNodeProduct()
    {
        return nodeProduct;
    }

    @OslcDescription("The Node Product Revision.")
    @OslcPropertyDefinition(TFSAdapterConstants.ENTERPRISE_CHANGE_MANAGEMENT_NAMESPACE + "nodeProductRevision")
    @OslcOccurs(Occurs.ZeroOrOne)
    @OslcTitle("Node Product Revision")
    public String getNodeProductRevision()
    {
        return nodeProductRevision;
    }
    
    @OslcDescription("The Corrected Product.")
    @OslcPropertyDefinition(TFSAdapterConstants.ENTERPRISE_CHANGE_MANAGEMENT_NAMESPACE + "correctedProduct")
    @OslcOccurs(Occurs.ZeroOrOne)
    @OslcTitle("Corrected Product")
    public String getCorrectedProduct()
    {
        return correctedProduct;
    }

    @OslcDescription("The Corrected Product Revision.")
    @OslcPropertyDefinition(TFSAdapterConstants.ENTERPRISE_CHANGE_MANAGEMENT_NAMESPACE + "correctedProductRevision")
    @OslcOccurs(Occurs.ZeroOrOne)
    @OslcTitle("Corrected Product Revision")
    public String getCorrectedProductRevision()
    {
        return correctedProductRevision;
    }
    
    @OslcDescription("The Corrected Node Product.")
    @OslcPropertyDefinition(TFSAdapterConstants.ENTERPRISE_CHANGE_MANAGEMENT_NAMESPACE + "correctedNodeProduct")
    @OslcOccurs(Occurs.ZeroOrOne)
    @OslcTitle("Corrected Node Product")
    public String getCorrectedNodeProduct()
    {
        return correctedNodeProduct;
    }

    @OslcDescription("The Corrected Node Product Revision.")
    @OslcPropertyDefinition(TFSAdapterConstants.ENTERPRISE_CHANGE_MANAGEMENT_NAMESPACE + "correctedNodeProductRevision")
    @OslcOccurs(Occurs.ZeroOrOne)
    @OslcTitle("Corrected Node Product Revision")
    public String getCorrectedNodeProductRevision()
    {
        return correctedNodeProductRevision;
    }

    @OslcDescription("The expected impact on the ISP")
    @OslcPropertyDefinition(TFSAdapterConstants.ENTERPRISE_CHANGE_MANAGEMENT_NAMESPACE + "expectedImpactOnISP")
    @OslcOccurs(Occurs.ZeroOrOne)
    @OslcTitle("Expected Impact On ISP")
    public String getExpectedImpactOnISP() {
        return expectedImpactOnISP;
    }

    @OslcDescription("A list of TR ids that are set as Duplicate to this ECR, e.g. 'TB12345{,TB12346,…}' ")
    @OslcPropertyDefinition(TFSAdapterConstants.ENTERPRISE_CHANGE_MANAGEMENT_NAMESPACE + "duplicateTRs")
    @OslcOccurs(Occurs.ZeroOrOne)
    @OslcTitle("Duplicate TRs")
    public String getDuplicateTRs() {
        return duplicateTRs;
    }
    
    @OslcDescription("Links to attachments")
    @OslcName("attachment")
    @OslcPropertyDefinition(TFSAdapterConstants.ENTERPRISE_CHANGE_MANAGEMENT_NAMESPACE + "attachment")
    @OslcTitle("Link to attachments")
    public Link[] getAttachments() {
        return attachments.toArray(new Link[attachments.size()]);
    }
    
    public void setAnswer(String answer) {
        this.answer = answer;
    }

    public void setAnswerCode(String answerCode) {
        this.answerCode = answerCode;
    }
    
    public void setFaultCode(String faultCode) {
        this.faultCode = faultCode;
    }
    
    public void setFirstTechnicalContact(String firstTechnicalContact) {
        this.firstTechnicalContact = firstTechnicalContact;
    }
    
    public void setProduct(String product)
    {
        this.product = product;
    }

    public void setProductRevision(String productRevision)
    {
        this.productRevision = productRevision;
    }

    public void setNodeProduct(String nodeProduct)
    {
        this.nodeProduct = nodeProduct;
    }

    public void setNodeProductRevision(String nodeProductRevision)
    {
        this.nodeProductRevision = nodeProductRevision;
    }
    
    public void setCorrectedProduct(String correctedProduct) {
        this.correctedProduct = correctedProduct;
    }
    
    public void setCorrectedProductRevision(String correctedProductRevision) {
        this.correctedProductRevision = correctedProductRevision;
    }
    
    public void setCorrectedNodeProduct(String correctedNodeProduct) {
        this.correctedNodeProduct = correctedNodeProduct;
    }
    
    public void setCorrectedNodeProductRevision(
            String correctedNodeProductRevision) {
        this.correctedNodeProductRevision = correctedNodeProductRevision;
    }

    public void setCurrentMho(String currentMho)
    {
        this.currentMho = currentMho;
    }

    public void setDiddet(String diddet)
    {
        this.diddet = diddet;
    }

    public void setFirstTechContactInfo(String firstTechContactInfo)
    {
        this.firstTechContactInfo = firstTechContactInfo;
    }

    public void setActivity(String activity)
    {
        this.activity = activity;
    }
    
    public void setCountry(String country) {
        this.country = country;
    }
    
    public void setCustomer(String customer) {
        this.customer = customer;
    }
    
    public void setSite(String site) {
        this.site = site;
    }
    
    public void setImpactOnISP(String impactOnISP) {
        this.impactOnISP = impactOnISP;
    }
    
    public void setPriority(String priority)
    {
        this.priority = priority;
    }

    public void setOwner(String owner)
    {
        this.owner = owner;
    } 
    
    public void setNotebook(String notebook) {
        this.notebook = notebook;
    }
    
    public void setProgressInfo(String progressInfo) {
        this.progressInfo = progressInfo;
    }
    
    public void setExpectedImpactOnISP(String expectedImpactOnISP) {
        this.expectedImpactOnISP = expectedImpactOnISP;
    }
    
    public void setDuplicateTRs(String duplicateTRs) {
        this.duplicateTRs = duplicateTRs;
    }
    
    public void setAttachments(final Link[] attachments) {
        this.attachments.clear();

        if (attachments != null) {
            this.attachments.addAll(Arrays
                    .asList(attachments));
        }
    }
    
    public void addAttachment(final Link attachment) {
        this.attachments.add(attachment);
    }

}

